version: '3'

services:
  selenoid:
    image: "aerokube/selenoid:latest-release"
    network_mode: bridge
    container_name: "selenoid"
    restart: always
    ports:
      - 4444:4444
    volumes:
      - "${PWD}/etc/selenoid:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:latest-release"
    network_mode: bridge
    container_name: "selenoid-ui"
    restart: always
    depends_on:
      - selenoid
    links:  # todo: refactor because links are deprecated
      - selenoid
    ports:
      - 8080:8080
    command: ["--selenoid-uri", "http://selenoid:4444"]

  jenkins:
    build: ./jenkins-image
    image: jenkins-with-docker
    network_mode: bridge
    container_name: "jenkins"
    volumes:
      - "/var/jenkins_home"
      - "/var/run/docker.sock.raw:/var/run/docker.sock"
    ports:
      - 8088:8080
      - 50000:50000
