version: '3'

services:
  selenoid:
    image: "aerokube/selenoid:1.10.0"
    network_mode: bridge
    restart: always
    ports:
      - "4444:4444"  
    volumes:
      - "$PWD/etc/selenoid:/etc/selenoid/"
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: ["-conf", "/etc/selenoid/browsers.json", "-limit", "4"]

  selenoid-ui:
    image: "aerokube/selenoid-ui:1.10.0"
    network_mode: bridge
    restart: always
    depends_on:
      - selenoid
    links:  # todo: refactor because links are deprecated
      - selenoid
    ports:
      - "8088:8080"
    command: ["--selenoid-uri", "http://selenoid:4444"]

  jenkins:
    image: "jenkins/jenkins"
    container_name: "jenkins"
    volumes:
      - "/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8080:8080
      - 50000:50000
